let surah =[]
function addSurah(name , to , page){
    surah.push(
        {
            [name]:{
                from: 1,
                to: to
            }
        }
    )
}

addSurah("الفاتحة" , 7,)
addSurah("البقرة" , 286)
addSurah("ال عمران" , 200)
addSurah("النساء" , 176)
addSurah("المائدة" , 120)
addSurah("الانعام" , 165)
addSurah("الاعراف" , 206)
addSurah("الانفال" , 75)
addSurah("التوبة" , 129)
addSurah("يونس" ,109)
addSurah("هود" ,123)
addSurah("يوسف" ,111)
addSurah("الرعد" ,43)
addSurah("ابراهيم" ,52)
addSurah("الحجر" ,99)
addSurah("النحل" ,128)
addSurah("الاسراء" ,111)
addSurah("الكهف" ,110)
addSurah("مريم" ,98)
addSurah("طه" ,135)
addSurah("الانبياء" ,112)
addSurah("الحج" ,78)
addSurah("المؤمنون" ,118)
addSurah("النور" ,64)
addSurah("الفرقان" ,77)
addSurah("الشعراء" ,227)
addSurah("النمل" ,93)
addSurah("القصص" ,88)
addSurah("العنكبوت" ,69)
addSurah("الروم" ,60)
addSurah("لقمان" ,34)
addSurah("السجدة" ,30)
addSurah("الأحزاب" ,73)
addSurah("سبا" ,54)
addSurah("فاطر" ,45)
addSurah("يس" ,83)
addSurah("الصافات" ,182)
addSurah("ص" ,88)
addSurah("الزمر" ,75)
addSurah("غافر" ,85)
addSurah("فصلت" ,54)
addSurah("الشورى" ,53)
addSurah("الزخرف" ,89)
addSurah("الدخان" ,59)
addSurah("الجاثية" ,37)
addSurah("الاحقاف" ,35)
addSurah("محمد" ,38)
addSurah("الفتح" ,29)
addSurah("الحجرات" ,18)
addSurah("ق" ,45)
addSurah("الذاريات" ,60)
addSurah("الطور" ,49)
addSurah("النجم" ,62)
addSurah("القمر" ,55)
addSurah("الرحمن" ,78)
addSurah("الواقعة" ,96)
addSurah("الحديد" ,29)
addSurah("المجادلة" ,22)
addSurah("الحشر" ,24)
addSurah("الممتحنة" ,13)
addSurah("الصف" ,14)
addSurah("الجمعة" ,11)
addSurah("المنافقون" ,11)
addSurah("التغابن" ,18)
addSurah("الطلاق" ,12)
addSurah("التحريم" ,12)
addSurah("الملك" ,30)
addSurah("القلم" ,52)
addSurah("الحاقة" ,52)
addSurah("المعارج" ,44)
addSurah("نوح" ,28)
addSurah("الجن" ,28)
addSurah("المزمل" ,20)
addSurah("المدثر" ,56)
addSurah("القيامة" ,40)
addSurah("الانسان" ,31)
addSurah("المرسلات" ,50)
addSurah("النبا" ,40)
addSurah("النازعات" ,46)
addSurah("عبس" ,42)
addSurah("التكوير" ,29)
addSurah("الانفطار" ,19)
addSurah("المطففين" ,36)
addSurah("الانشقاق" ,25)
addSurah("البروج" ,22)
addSurah("الطارق" ,17)
addSurah("الاعلى" ,19)
addSurah("الغاشية" ,26)
addSurah("الفجر" ,30)
addSurah("البلد" ,20)
addSurah("الشمس" ,15)
addSurah("الليل" ,21)
addSurah("الضحى" ,11)
addSurah("الشرح" ,8)
addSurah("التين" ,8)
addSurah("العلق" ,19)
addSurah("القدر" ,5)
addSurah("البينة" ,8)
addSurah("الزلزلة" ,8)
addSurah("العاديات" ,11)
addSurah("القارعة" ,11)
addSurah("العصر" ,3)
addSurah("الهمزة" ,9)
addSurah("الفيل" ,5)
addSurah("قريش" ,4)
addSurah("الماعون" ,7)
addSurah("الكوثر" ,3)
addSurah("الكافرون" ,6)
addSurah("النصر" ,3)
addSurah("المسد" ,5)
addSurah("الإخلاص" ,4)
addSurah("الفلق" ,5)
addSurah("الناس" ,6)
export default surah